In [5]:
import pandas as pd

In [8]:
customers = pd.read_csv(r"C:\Users\PC\Desktop\ATR\data\customers.csv")
extra = pd.read_csv(r"C:\Users\PC\Desktop\ATR\data\extra_orders.csv")
orders = pd.read_csv(r"C:\Users\PC\Desktop\ATR\data\orders.csv")

In [10]:
customers

   customer_id     name   city  age
0            1      Ali  Cairo   22
1            2     Sara   Giza   28
2            3     Omar  Cairo   35
3            4     Mona   Alex   24
4            5  Youssef   Giza   31
5            6     Nour  Cairo   27

In [12]:
orders

   order_id  customer_id  amount
0       101            1     250
1       102            2     400
2       103            1     150
3       104            3     700
4       105            5     300
5       106            2     500
6       107            4     350

In [11]:
extra

   order_id  customer_id  amount
0       108            3     450
1       109            6     275

In [18]:
age_higherthan_25 = customers[customers["age"]>25]
age_higherthan_25

   customer_id     name   city  age
1            2     Sara   Giza   28
2            3     Omar  Cairo   35
4            5  Youssef   Giza   31
5            6     Nour  Cairo   27

In [19]:
from_cairo = customers[customers["city"] == "Cairo"]
from_cairo

   customer_id  name   city  age
0            1   Ali  Cairo   22
2            3  Omar  Cairo   35
5            6  Nour  Cairo   27

In [22]:
both_condations = customers[(customers["age"]>25) & (customers["city"] == "Cairo")]
both_condations

   customer_id  name   city  age
2            3  Omar  Cairo   35
5            6  Nour  Cairo   27

In [ ]:
ordedrs_higherthanORequal_300 = orders[orders["amount"] >= 300]
ordedrs_higherthanORequal_300

   order_id  customer_id  amount
1       102            2     400
3       104            3     700
4       105            5     300
5       106            2     500
6       107            4     350

In [29]:
customers.sort_values(by= "age" , ascending=True)

   customer_id     name   city  age
0            1      Ali  Cairo   22
3            4     Mona   Alex   24
5            6     Nour  Cairo   27
1            2     Sara   Giza   28
4            5  Youssef   Giza   31
2            3     Omar  Cairo   35

In [30]:
customers.sort_values(by= "age" , ascending=False)

   customer_id     name   city  age
2            3     Omar  Cairo   35
4            5  Youssef   Giza   31
1            2     Sara   Giza   28
5            6     Nour  Cairo   27
3            4     Mona   Alex   24
0            1      Ali  Cairo   22

In [31]:
customers.sort_values(by=["city","age"] , ascending= [True,False])

   customer_id     name   city  age
3            4     Mona   Alex   24
2            3     Omar  Cairo   35
5            6     Nour  Cairo   27
0            1      Ali  Cairo   22
4            5  Youssef   Giza   31
1            2     Sara   Giza   28

In [46]:
costumers = customers.set_index("customer_id")
costumers

                name   city  age
customer_id
1                Ali  Cairo   22
2               Sara   Giza   28
3               Omar  Cairo   35
4               Mona   Alex   24
5            Youssef   Giza   31
6               Nour  Cairo   27

In [47]:
customers.loc[3]

customer_id       4
name           Mona
city           Alex
age              24
Name: 3, dtype: object

In [ ]:
costumers.iloc[0]

customer_id        1
name             Ali
city           Cairo
age               22
Name: 0, dtype: object

In [57]:
group = costumers.groupby("city")
group["age"].mean()

city
Alex     24.0
Cairo    28.0
Giza     29.5
Name: age, dtype: float64

In [63]:
group["name"].count()

city
Alex     1
Cairo    3
Giza     2
Name: name, dtype: int64

In [64]:
group1 = orders.groupby("customer_id")
group1["amount"].sum()

customer_id
1    400
2    900
3    700
4    350
5    300
Name: amount, dtype: int64

In [66]:
group1["amount"].agg(["sum","mean","max"])

             sum   mean  max
customer_id
1            400  200.0  250
2            900  450.0  500
3            700  700.0  700
4            350  350.0  350
5            300  300.0  300